Added GitHub Pull Request Template
ministryofjustice/apvs pull request #65
Opened 2016-09-19 13:24 UTC by tswann

- Includes code review checklist
- Basic template to provide consistent structure for PRs

Please also review the ODP Code Quality document - this is linked in the Technical Overview of the wiki.

2016-09-19 14:41 UTC, tmrowe commented on .github/PULL_REQUEST_TEMPLATE
> +
Options to add:
Is well factored?
Is maintainable?
Is documented?

2016-09-19 14:45 UTC, tmrowe commented on .github/PULL_REQUEST_TEMPLATE
> +
High level description

2016-09-19 14:45 UTC, tmrowe commented on .github/PULL_REQUEST_TEMPLATE
> +
Third heading:
Listing bullets with changes made.

2016-09-19 14:47 UTC, tmrowe commented on .github/PULL_REQUEST_TEMPLATE
> +
Modified Areas

2016-09-19 14:48 UTC, tmrowe commented on .github/PULL_REQUEST_TEMPLATE
> +A checklist is for the benefit of the primary reviewer - aka __YOU__ - the person submitting the pull request.
This checklist...
A checklist for the...

2016-09-19 14:48 UTC, tmrowe requested changes

2016-09-20 10:42 UTC, tswann commented
Hi @tmrowe - please see updates applied in latest commit.

Thanks,
Tom

2016-09-20 10:56 UTC, tmrowe approved these changes

2016-09-20 10:56 UTC, merged